-- Daily snapshots for research measurement baseline + trend tracking
CREATE TABLE IF NOT EXISTS daily_snapshots (
  id INT AUTO_INCREMENT PRIMARY KEY,
  snapshot_date DATE NOT NULL,
  scope_type ENUM('system','school','affiliation') NOT NULL DEFAULT 'system',
  scope_id VARCHAR(20) NULL,
  total_students INT DEFAULT 0,
  students_with_vehicle INT DEFAULT 0,
  students_with_parent INT DEFAULT 0,
  total_vehicles INT DEFAULT 0,
  vehicles_with_insurance INT DEFAULT 0,
  vehicles_inspected INT DEFAULT 0,
  vehicles_passed INT DEFAULT 0,
  morning_total INT DEFAULT 0,
  morning_done INT DEFAULT 0,
  evening_total INT DEFAULT 0,
  evening_done INT DEFAULT 0,
  emergency_count INT DEFAULT 0,
  active_users INT DEFAULT 0,
  total_users INT DEFAULT 0,
  is_baseline BOOLEAN DEFAULT FALSE,
  baseline_note VARCHAR(255) NULL,
  run_type ENUM('manual','auto','baseline') DEFAULT 'manual',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by INT NULL,
  UNIQUE KEY uk_date_scope (snapshot_date, scope_type, scope_id),
  INDEX idx_date (snapshot_date),
  INDEX idx_baseline (is_baseline)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
